"""UI metadata for parameters confirmed from the three upstream inference APIs."""

from __future__ import annotations

from copy import deepcopy


def _p(name, label, kind, default=None, *, required=False, minimum=None, maximum=None,
       choices=None, advanced=False, restart_required=False, description="", tuning=""):
    value = {
        "name": name, "label": label, "type": kind, "default": default,
        "required": required, "advanced": advanced,
        "restart_required": restart_required,
        "description_zh": description, "tuning_zh": tuning,
    }
    if minimum is not None:
        value["minimum"] = minimum
    if maximum is not None:
        value["maximum"] = maximum
    if choices is not None:
        value["choices"] = choices
    return value


ENGINE_PARAMETERS = {
    "indextts2": [
        _p("emotion_mode", "情感控制方式", "select", "audio", choices=["audio", "text", "vector", "random"],
           description="界面派生模式：情感音频、情感文本、八维向量、随机情感四选一。",
           tuning="用于明确互斥关系；切换模式会停用其他三类情感输入。"),
        _p("speaker_audio", "说话人参考音频", "file", required=True,
           description="决定音色与说话人特征的参考音频，源码最多截取前 15 秒。",
           tuning="换参考音频会改变音色；优先使用单人、干净、无混响的人声。"),
        _p("emotion_audio", "情感参考音频", "file", None,
           description="从另一段音频提取情感；留空时使用说话人参考音频。",
           tuning="与情感文本或情感向量互斥；用于迁移语气而尽量保持说话人音色。"),
        _p("emotion_alpha", "情感权重", "number", 1.0, minimum=0.0, maximum=1.0,
           description="对应 IndexTTS2 的 emo_alpha。",
           tuning="越大越接近情感参考；使用情感向量时会按此值缩放向量。"),
        _p("emotion_text", "情感描述文本", "text", None,
           description="启用后由模型从描述中自动推断八维情感。",
           tuning="适合用“开心、轻快但克制”等自然语言控制；会停用情感参考音频。"),
        _p("emotion_vector", "八维情感向量", "number_array", None,
           description="顺序为开心、愤怒、悲伤、恐惧、厌恶、低落、惊讶、平静。",
           tuning="八项之和超过 0.8 时源码会自动等比缩放；会停用情感参考音频。"),
        _p("use_random", "随机情感采样", "boolean", False, advanced=True,
           description="允许源码随机生成情感向量。", tuning="复现结果时关闭并设置固定采样参数。"),
        _p("interval_silence", "内部片段静音", "integer", 200, minimum=0, advanced=True,
           description="IndexTTS2 内部分段之间插入的毫秒静音。",
           tuning="本软件已外部分段，通常保持 0 到 200；过大会显得停顿生硬。"),
        _p("max_text_tokens_per_segment", "模型内部最大文本 Token", "integer", 120, minimum=20, advanced=True,
           description="IndexTTS2 自身二次切分的 Token 上限。",
           tuning="显存不足或尾部截断时调低；过低可能破坏韵律连贯性。"),
        _p("stream_return", "流式返回", "boolean", False, advanced=True,
           description="让 IndexTTS2 在生成时逐块产出；任务仍会等待该段完整写入后再进入合并。"),
        _p("quick_streaming_tokens", "快速流式 Token", "integer", 0, minimum=0, advanced=True,
           description="传给 IndexTTS2 分段器的快速流式 Token 配置。", tuning="非流式保持 0；过小会增加边界。"),
        _p("do_sample", "采样生成", "boolean", True, advanced=True,
           description="是否使用随机采样。", tuning="关闭有助稳定复现，但表达可能更单一。"),
        _p("top_p", "Top P", "number", 0.8, minimum=0.0, maximum=1.0, advanced=True,
           description="核采样累计概率阈值。", tuning="降低更稳定，提高更多样但更易出现异常读法。"),
        _p("top_k", "Top K", "integer", 30, minimum=1, advanced=True,
           description="每步仅在概率最高的 K 个候选中采样。", tuning="降低更保守，提高更多样。"),
        _p("temperature", "采样温度", "number", 0.8, minimum=0.01, advanced=True,
           description="控制采样分布的随机程度。", tuning="异常发音多时降低；表达呆板时小幅提高。"),
        _p("length_penalty", "长度惩罚", "number", 0.0, advanced=True,
           description="影响生成序列长度偏好。", tuning="保持默认；只在持续过短或拖尾时微调。"),
        _p("num_beams", "束搜索数量", "integer", 3, minimum=1, advanced=True,
           description="候选搜索束数量。", tuning="提高可能更稳定但更慢、更占显存。"),
        _p("repetition_penalty", "重复惩罚", "number", 10.0, minimum=1.0, advanced=True,
           description="抑制语音 Token 重复。", tuning="重复卡音时提高；吞字或过度收缩时降低。"),
        _p("max_mel_tokens", "最大声学 Token", "integer", 1500, minimum=100, advanced=True,
           description="单个内部片段可生成的最大声学 Token 数。", tuning="尾部被截断时提高；会增加显存和耗时。"),
        _p("model_dir", "模型目录", "directory", None, advanced=True, restart_required=True,
           description="包含 config.yaml、gpt.pth、s2mel.pth 等文件。"),
        _p("device", "计算设备", "text", "cuda:0", advanced=True, restart_required=True,
           description="例如 cuda:0、cpu、mps 或 xpu。"),
        _p("use_fp16", "FP16 半精度", "boolean", True, advanced=True, restart_required=True,
           description="CUDA 上以半精度推理以降低显存。", tuning="出现数值异常时关闭；CPU 会被源码强制关闭。"),
        _p("use_cuda_kernel", "CUDA 融合内核", "boolean", True, advanced=True, restart_required=True,
           description="启用 BigVGAN 自定义 CUDA 融合激活。", tuning="编译或兼容问题时关闭。"),
        _p("use_deepspeed", "DeepSpeed", "boolean", False, advanced=True, restart_required=True,
           description="使用 DeepSpeed 推理包装。", tuning="环境未安装或加载失败时关闭。"),
        _p("use_accel", "GPT2 加速引擎", "boolean", False, advanced=True, restart_required=True,
           description="启用 IndexTTS2 GPT2 加速实现。", tuning="首次验证建议关闭，稳定后再开启比较速度。"),
        _p("use_torch_compile", "torch.compile", "boolean", False, advanced=True, restart_required=True,
           description="编译 s2mel 优化推理。", tuning="首次运行会很慢；遇到图编译问题时关闭。"),
    ],
    "voxcpm": [
        _p("control", "声音设计指令", "text", None,
           description="源码会以“(指令)正文”形式交给 VoxCPM2。",
           tuning="可描述年龄、音色、语速、情绪；与带文本的续写参考同时使用可能互相干扰。"),
        _p("prompt_audio", "续写提示音频", "file", None,
           description="续写模式的提示音频，必须同时填写对应文本。"),
        _p("prompt_text", "提示音频文本", "text", None,
           description="prompt_audio 中实际说出的文字。", tuning="必须准确，否则音色和内容对齐会变差。"),
        _p("reference_audio", "音色参考音频", "file", None,
           description="VoxCPM2 的结构化音色克隆参考，可单独使用。"),
        _p("cfg_value", "CFG 引导强度", "number", 2.0, minimum=0.0, advanced=True,
           description="生成模型的 classifier-free guidance 强度。", tuning="提高更遵循条件但过高可能失真；源码 CLI 推荐约 1 到 3。"),
        _p("inference_timesteps", "扩散采样步数", "integer", 10, minimum=1, advanced=True,
           description="DiT 推理步数。", tuning="增加通常更慢且可能更细致；源码 CLI 推荐约 4 到 20。"),
        _p("min_len", "最小生成长度", "integer", 2, minimum=1, advanced=True,
           description="底层生成的最小长度参数。", tuning="通常保持默认。"),
        _p("max_len", "最大生成长度", "integer", 4096, minimum=32, advanced=True,
           description="底层生成最大 Token 长度。", tuning="截断时提高，显存不足时降低。"),
        _p("normalize", "文本规范化", "boolean", False,
           description="生成前执行 VoxCPM 文本规范化。", tuning="含数字、日期、单位时建议开启。"),
        _p("denoise", "参考音频降噪", "boolean", False,
           description="对提示或参考音频运行 ZipEnhancer。", tuning="参考音频干净时关闭可避免音色细节损失。"),
        _p("retry_badcase", "异常样本自动重试", "boolean", True, advanced=True,
           description="VoxCPM 内部检测异常时重新生成。"),
        _p("retry_badcase_max_times", "内部异常重试次数", "integer", 3, minimum=0, advanced=True,
           description="VoxCPM 内部 badcase 最大重试次数；独立于任务级失败重试。"),
        _p("retry_badcase_ratio_threshold", "异常时长比阈值", "number", 6.0, minimum=0.1, advanced=True,
           description="音频时长与文本长度比超过阈值时判为异常。", tuning="误判短句时提高；异常拖长未检出时降低。"),
        _p("streaming", "流式生成", "boolean", False, advanced=True,
           description="调用 VoxCPM generate_streaming 逐块生成；任务会汇总该段后写 WAV。"),
        _p("seed", "随机种子", "integer", None, advanced=True,
           description="固定后有助复现同一生成结果。"),
        _p("model_path", "本地模型目录", "directory", None, advanced=True, restart_required=True,
           description="包含 VoxCPM/VoxCPM2 config.json 与权重的本地目录；留空使用 hf_model_id 缓存。"),
        _p("hf_model_id", "模型标识", "text", "openbmb/VoxCPM2", advanced=True, restart_required=True,
           description="Hugging Face 模型 ID，当前源码默认 openbmb/VoxCPM2。"),
        _p("cache_dir", "模型缓存目录", "directory", None, advanced=True, restart_required=True),
        _p("local_files_only", "仅使用本地文件", "boolean", True, advanced=True, restart_required=True,
           description="禁止运行时联网下载。"),
        _p("device", "计算设备", "text", "cuda:0", advanced=True, restart_required=True),
        _p("enable_denoiser", "加载降噪模型", "boolean", True, advanced=True, restart_required=True,
           description="启动时加载 ZipEnhancer；关闭可节省资源。"),
        _p("zipenhancer_model_id", "降噪模型", "text", "iic/speech_zipenhancer_ans_multiloss_16k_base", advanced=True, restart_required=True),
        _p("optimize", "编译优化", "boolean", True, advanced=True, restart_required=True,
           description="加载时执行 torch.compile 和预热。", tuning="启动或编译失败时关闭。"),
        _p("lora_weights_path", "LoRA 权重", "file", None, advanced=True, restart_required=True,
           description="可选 LoRA 权重文件或包含 lora_weights.ckpt 的目录。"),
        _p("lora_r", "LoRA Rank", "integer", 32, minimum=1, advanced=True, restart_required=True,
           description="LoRA 低秩维度；必须与权重训练配置一致。"),
        _p("lora_alpha", "LoRA Alpha", "integer", 16, minimum=1, advanced=True, restart_required=True,
           description="LoRA 缩放系数；必须与权重训练配置一致。"),
        _p("lora_dropout", "LoRA Dropout", "number", 0.0, minimum=0.0, maximum=1.0, advanced=True, restart_required=True),
        _p("lora_disable_lm", "LoRA 不作用于 LM", "boolean", False, advanced=True, restart_required=True),
        _p("lora_disable_dit", "LoRA 不作用于 DiT", "boolean", False, advanced=True, restart_required=True),
        _p("lora_enable_proj", "LoRA 作用于投影层", "boolean", False, advanced=True, restart_required=True),
    ],
    "gpt_sovits": [
        _p("reference_audio", "参考音频", "file", required=True,
           description="必填，用于提取目标说话人音色。"),
        _p("text_language", "正文语言", "select", "auto", choices=["auto", "auto_yue", "zh", "en", "ja", "yue", "ko", "all_zh", "all_ja", "all_yue", "all_ko"],
           description="控制正文的语言识别/混合语言切分策略。"),
        _p("prompt_text", "参考音频文本", "text", "",
           description="参考音频中说出的文字；准确填写通常可提升克隆质量。"),
        _p("prompt_language", "参考文本语言", "select", "auto", choices=["auto", "auto_yue", "zh", "en", "ja", "yue", "ko", "all_zh", "all_ja", "all_yue", "all_ko"]),
        _p("aux_reference_audios", "辅助参考音频", "file_array", None,
           description="多段辅助参考，用于融合更多音色信息。"),
        _p("top_k", "Top K", "integer", 15, minimum=1, advanced=True,
           description="语义 Token 采样候选数。", tuning="降低更稳定，提高更多样。"),
        _p("top_p", "Top P", "number", 1.0, minimum=0.0, maximum=1.0, advanced=True,
           description="核采样累计概率阈值。"),
        _p("temperature", "采样温度", "number", 1.0, minimum=0.01, advanced=True,
           description="控制随机度。", tuning="错读或不稳定时降低。"),
        _p("text_split_method", "模型内部切分方式", "select", "cut5", choices=["cut0", "cut1", "cut2", "cut3", "cut4", "cut5"], advanced=True,
           description="GPT-SoVITS 内置切分方法；本软件外部已按段处理。", tuning="希望保持外部分段边界时用 cut0；兼容默认用 cut5。"),
        _p("batch_size", "推理批大小", "integer", 1, minimum=1, advanced=True,
           description="并行处理文本片段数量。", tuning="增大可提速但增加显存。"),
        _p("batch_threshold", "批次分桶阈值", "number", 0.75, minimum=0.0, advanced=True,
           description="长度差异超过阈值时拆分批次。"),
        _p("split_bucket", "长度分桶", "boolean", True, advanced=True,
           description="按长度分桶以提高批处理效率。"),
        _p("speed_factor", "语速倍率", "number", 1.0, minimum=0.25, maximum=4.0,
           description="控制合成语速；大于 1 更快。"),
        _p("fragment_interval", "片段间隔", "number", 0.3, minimum=0.0, advanced=True,
           description="GPT-SoVITS 内部片段间隔秒数。"),
        _p("seed", "随机种子", "integer", -1, advanced=True,
           description="-1 表示随机；固定整数便于复现。"),
        _p("parallel_infer", "并行推理", "boolean", True, advanced=True,
           description="启用语义模型并行批推理；非流式任务通常应开启。"),
        _p("repetition_penalty", "重复惩罚", "number", 1.35, minimum=1.0, advanced=True,
           description="抑制重复语义 Token。", tuning="重复卡音时提高，吞字时降低。"),
        _p("sample_steps", "V3 采样步数", "integer", 32, minimum=1, advanced=True,
           description="SoVITS V3 的采样步数；其他版本可能不使用。"),
        _p("super_sampling", "V3 超采样", "boolean", False, advanced=True,
           description="SoVITS V3 超采样输出；增加处理耗时。"),
        _p("media_type", "输出封装", "readonly", "wav", advanced=True,
           description="上游 API 支持 wav/raw/ogg/aac；本软件长音频管线固定使用 WAV 以便无损合并。"),
        _p("return_fragment", "分片返回", "boolean", False, advanced=True,
           description="对应上游旧版最佳质量分片返回；完整段落仍在后台汇总。"),
        _p("fixed_length_chunk", "固定长度流式块", "boolean", False, advanced=True,
           description="固定流式块可加快响应，但上游注明质量更低。"),
        _p("streaming_mode", "流式模式", "select", 0, choices=[0, 1, 2, 3], advanced=True,
           description="0 关闭；1 最佳质量分片；2 中等质量流式；3 更快但质量较低。",
           tuning="本软件按完整 WAV 段落合并，第一版建议保持 0。"),
        _p("overlap_length", "流式重叠 Token", "integer", 2, minimum=0, advanced=True,
           description="流式片段的语义 Token 重叠长度。"),
        _p("min_chunk_length", "流式最小片段 Token", "integer", 16, minimum=1, advanced=True,
           description="影响流式输出块大小。"),
        _p("tts_config_path", "推理配置 YAML", "file", None, advanced=True, restart_required=True,
           description="定义模型版本、设备与默认权重路径。"),
        _p("device", "计算设备覆盖", "text", None, advanced=True, restart_required=True,
           description="可选；覆盖 YAML 中的 device。"),
        _p("is_half", "半精度覆盖", "boolean", None, advanced=True, restart_required=True,
           description="可选；覆盖 YAML 中的 is_half。"),
        _p("t2s_weights_path", "GPT 权重", "file", None, advanced=True, restart_required=True),
        _p("vits_weights_path", "SoVITS 权重", "file", None, advanced=True, restart_required=True),
        _p("bert_base_path", "BERT 模型目录", "directory", None, advanced=True, restart_required=True),
        _p("cnhuhbert_base_path", "CNHuBERT 模型目录", "directory", None, advanced=True, restart_required=True),
        _p("version", "模型版本", "readonly", "auto", advanced=True,
           description="只读能力提示；实际版本由 SoVITS 权重和推理 YAML 检测，可为 v1/v2/v3/v4/v2Pro/v2ProPlus。"),
    ],
}


ENGINE_INFO = {
    "indextts2": {"id": "indextts2", "name": "IndexTTS2", "project_path": "F:/AI/peyin/indextts2"},
    "voxcpm": {"id": "voxcpm", "name": "VoxCPM2", "project_path": "F:/AI/peyin/VoxCPM"},
    "gpt_sovits": {"id": "gpt_sovits", "name": "GPT-SoVITS", "project_path": "F:/AI/peyin/GPT-SoVITS"},
}


def engine_catalog() -> list[dict]:
    catalog = []
    for engine_id, info in ENGINE_INFO.items():
        item = deepcopy(info)
        item["parameters"] = deepcopy(ENGINE_PARAMETERS[engine_id])
        catalog.append(item)
    return catalog


def defaults_for(engine_id: str) -> dict:
    return {p["name"]: deepcopy(p["default"]) for p in ENGINE_PARAMETERS[engine_id]}
